# Generated by Django 2.2.3 on 2019-12-19 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comments_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='create_time',
        ),
        migrations.AddField(
            model_name='comments',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='url',
            field=models.URLField(blank=True, verbose_name='网址'),
        ),
    ]
