# Generated by Django 2.2.3 on 2019-12-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BooleanField(choices=[(0, '男'), (1, '女')], default=1, max_length=1, verbose_name='性别')),
                ('school', models.CharField(max_length=100, verbose_name='学校')),
                ('addr', models.CharField(max_length=200, verbose_name='住址')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
