# Generated by Django 2.2.3 on 2019-12-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('age', models.IntegerField(max_length=50, verbose_name='年龄')),
                ('sex', models.BooleanField(verbose_name='性别')),
                ('address', models.CharField(max_length=200, verbose_name='住址')),
                ('school', models.CharField(max_length=100, verbose_name='学校')),
            ],
            options={
                'verbose_name': '基础信息',
                'verbose_name_plural': '基础信息',
            },
        ),
    ]
