# Generated by Django 2.2.3 on 2019-12-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_formtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormTest',
        ),
    ]
